
services:
  makeupbynuri:
    build:
      context: .
      target: runner
    container_name: makeupbynuri
    restart: unless-stopped
    ports:
      - "3003:3000"  # Expose the service on port 3003
    volumes:
      - ./db:/app/db  # Mount the database directory to persist changes
    env_file:
      - .env
    environment:
      - NODE_ENV=production
